zabbix:
  url: https://localhost/zabbix
  username: zabbix
  password: zabbix
  hostgroup: Switches
  map:
    name: Network Map
    width: 1275
    height: 690
  inventory_fields:
    - model
snmp:
  community: public
iconmap:
  Switch: switch.png
graphviz:
  imagepath: .
  attributes:
    graph:
      dpi: 100
      layout: dot
      fontname: Arial
      fontsize: 8
    node:
      fontname: Helvetica
      fontsize: 8
      fontcolor: "#000000"
      shape: none
      width: 0.8
      height: 0.6
      fixedsize: true
    edge:
      fontname: Arial
      fontsize: 8
      color: "#4488dd"
      fontcolor: "#ff0000"
    linkspeed:
    100:
      penwidth: 1
    1000:
      penwidth: 2
  file: netowrk-map.gv
  label_template: $zbx_hostname\n$model
  edge_label: false
