zabbix:
  url: https://localhost/zabbix
  username: zabbix
  password: zabbix
  hostgroup: Switches
  map:
    name: Network Map
    width: 1275
    height: 690
    default_icon: Switch_(24)
  inventory_fields:
    - model
snmp:
  community: public
iconmap:
  Switch: switch.png
graphviz:
  imagepath: .
  attributes:
    graph:
      dpi: 100
      layout: dot
      fontname: Arial
      fontsize: 8
      pad: 0.5
      nodesep: 0.25
    node:
      fontname: Helvetica
      fontsize: 8
      fontcolor: "#000000"
      shape: none
      width: 1
      height: 1
      fixedsize: true
    edge:
      fontname: Arial
      fontsize: 8
      color: "#4488dd"
      fontcolor: "#ff0000"
  linkspeed:
    100:
      penwidth: 0.75
    1000:
      penwidth: 1.5
  file: netowrk-map.gv
  imagefile: netowrk-map.png
  node_label_template: "\n\n\n\n\n$zabbix_name\n$model"
  edge_label: false
